// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDhDvRi-3VaBodOjnjUh9L9_jQszFEEqM',
    appId: '1:436209905733:web:71edcb8d8769f960dbb32c',
    messagingSenderId: '436209905733',
    projectId: 'shorebird-test-app-f10c0',
    authDomain: 'shorebird-test-app-f10c0.firebaseapp.com',
    storageBucket: 'shorebird-test-app-f10c0.firebasestorage.app',
    measurementId: 'G-GPPCMDCBV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvw1r9msQcoayNTq8KbN_duoibSZljpII',
    appId: '1:436209905733:android:deda20ff6964fb83dbb32c',
    messagingSenderId: '436209905733',
    projectId: 'shorebird-test-app-f10c0',
    storageBucket: 'shorebird-test-app-f10c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi3QZhZCm-ttOA8jYfA9WyXD8IMY8OuxA',
    appId: '1:436209905733:ios:2078480eb9462bf3dbb32c',
    messagingSenderId: '436209905733',
    projectId: 'shorebird-test-app-f10c0',
    storageBucket: 'shorebird-test-app-f10c0.firebasestorage.app',
    iosBundleId: 'com.example.shorebirdTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi3QZhZCm-ttOA8jYfA9WyXD8IMY8OuxA',
    appId: '1:436209905733:ios:2078480eb9462bf3dbb32c',
    messagingSenderId: '436209905733',
    projectId: 'shorebird-test-app-f10c0',
    storageBucket: 'shorebird-test-app-f10c0.firebasestorage.app',
    iosBundleId: 'com.example.shorebirdTestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDhDvRi-3VaBodOjnjUh9L9_jQszFEEqM',
    appId: '1:436209905733:web:638a2e3123b8900ddbb32c',
    messagingSenderId: '436209905733',
    projectId: 'shorebird-test-app-f10c0',
    authDomain: 'shorebird-test-app-f10c0.firebaseapp.com',
    storageBucket: 'shorebird-test-app-f10c0.firebasestorage.app',
    measurementId: 'G-0H7TBVRB59',
  );
}
